### ISSUE TITLE
question

### ISSUE THREAD

**Issue by echizent4** [comsave/salesforce-outbound-message-bundle#2]
Hi, I have a quiestion about this setting:

`comsave_salesforce_outbound_message:
    wsdl_directory: 'path/with/your/wsdl/files'
    document_paths:
        Account:
            path: 'path/to/document/Account'
        Product2:
            path: 'path/to/document/Product'`

Account and Product2 are a classes? or salesforce objects?
In wsdl directory I store workflow wsdls? I not have to specify THE wsdl's workflow  
with whom I want to work???

THX.

**Comment by Dirk-Scholten** [comment]
Hey @echizent4 

Account and Product2 are indeed Salesforce objects. I chose these two as an example because they are standard Salesforce objects. If you have a custom object you would use the Salesforce name for that. Something like: `CustomObject__c`.

In the wsdl directory you indeed store the wsdls that belong to your outbound message. They would have the name of the Salesforce object(s) that you want to sync. So for example: `Product2.wsdl` or `CustomObject__c.wsdl`

**Comment by echizent4** [comment]
@Dirk-Scholten 

Thx for answer. This bundle doesn´t work with enterprise or partner wsdl??.
In ur example Product2.wsdl and CustomObject__c.wsdl are in a other directory than outbound message, or can storage in the same directory??

And, i have issues to install the bundle, but maybe are dependencies problems.

**Comment by Dirk-Scholten** [comment]
Hey,

The bundle works with all enterprise, partners and sandbox of Salesforce. The wsdl that you want to put in the folder is the wsdl of the outbound message. You can find that wsdl on the outbound message itself. I've included a screenshot here:  ![alt text](https://i.imgur.com/Xm496Ac.png "Click for WSDL")

If you click the 'Click for WSDL' link it will generate the wsdl you need. This is possible for enterprise, sandbox or whatever environment you are using. 

You can put the wsdl in any directory you want. I suggest keeping it a separate directory for overview in your project. Just make sure that all of them are in the one folder that you point to in your configuration.

If you have any more questions or suggestions feel free to post!

**Comment by echizent4** [comment]
@Dirk-Scholten, I ask about enterprise or partnert wsdl, because I always work with this, and in this bundle I dont know where configure. Also i never generate a specific custom object wsdl.

And is my first time trying to work with web service and workflows form Salesforce.

Thx.
